server:
  port: 8093
  servlet:
    context-path: "/api"
spring:
  application:
    name: aop_demo
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: password
    driver-class-name: org.h2.Driver